import { useState } from "react";

const [formData, setFormData] = useState({
        employeeCode: 'EMP-2026-8942',
        password: '123456',
        confirmPassword: '123456',
        role: 'Employee',
        isAppAdmin: false,
        status: 'Active',
        name: 'Aarav Sharma',
        email: 'aarav.sharma@example.com',
        mobileNumber: '9820012345',
        alternateMobileNumber: '9820054321',
        gender: 'Male',
        bloodGroup: 'B+',
        dateOfBirth: '1998-11-14',
        maritalStatus: 'Married',
        fatherName: 'Ramesh Sharma',
        motherName: 'Kavita Sharma',
        address: {
            current: { address: '702, Silver Oaks Towers, Andheri West', pinCode: '400053', state: 'Maharashtra', district: 'Mumbai', city: 'Mumbai' },
            permanent: { address: 'Flat 4, Shanti Niwas, Erandwane', pinCode: '411004', state: 'Maharashtra', district: 'Pune', city: 'Pune' }
        },
        joiningDate: '2026-07-01',
        department: 'Engineering',
        position: 'Software Engineer',
        isLeadershipRole: false,
        salary: '65000',
        fixedAllowance: '12000',
        managerId: 'mgr_789456123987',
        experienceType: 'Experienced',
        totalExperienceYears: '3.5',
        lastCompanyName: 'TechSolutions Pvt Ltd',
        hscPercent: '88.5',
        graduationCourse: 'B.E. Computer Science',
        graduationPercent: '78.2',
        postGraduationCourse: '',
        postGraduationPercent: '',
        aadhaarNumber: '000000000000', // Dummy representation
        panNumber: 'XYZPD9876Q',
        accountHolderName: 'Aarav Sharma',
        bankName: 'ICICI Bank',
        accountNumber: '987654321098',
        ifsc: 'ICIC0000104',
        branch: 'Mumbai - Andheri',
        emergencyContactName: 'Ramesh Sharma',
        emergencyContactRelationship: 'Father',
        emergencyContactMobile: '9820012346',
        emergencyContactAddress: '702, Silver Oaks Towers, Andheri West, Mumbai',
        hasDisease: 'No',
        diseaseName: '',
        diseaseType: '',
        diseaseSince: '',
        medicinesRequired: '',
        doctorName: '',
        doctorContact: '',
    });